server:
  port: 8080

spring:
  profiles:
    default: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 55000



  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

  api-docs:
    path: /api-docs
    version: openapi_3_0
    enabled: true
  default-produces-media-type: application/json
  pre-loading-enabled: true


#logging:
#  config: classpath:logback-spring.xml
